language: python

branches:
  only:
  - master

python:
  - "3.6"

install:
  - sudo apt-get update
  - sudo apt-get install -y bash
  - pip install streamlink

env:
  global:
    - secure: "fMcrpBqvdgU9OyN25W9fhTHS/FnVkHoy0Vtc0Di32Xc0phaCA105mKRB0wEblPER0sDJucM1Ppn6j5W/Pdjebt6jZj8yUldj5OCDmMk0Psb3aHcutxH+oVjJ6nGYUyxK+nYrktlHAt/n2ofpO3/V3OfOMKCc0GCYKCc2ED2JNwRfE9owrj47Bw2gsF7et4/Vlibq/xkCwUnzvFpaRm1LyYL3ttoUb03o0CtITsvfSug5qZKnwTQPAaYx13w1zTBGb7VnYWL9jwcHO5CzXFzWUOYLiPuk++k2O4KDLJTS9TJpkAgdlUpEcf7TbjzA+p70FMtRqhZJgvHbyMKw1s9qWKL9ZJTbcDDkqq2ivDVtW3wqlB2tTxV7PD1oyxPGnrJy1LNMriKA4A2IYLlomQwmW71HZLS3kTpzzGdKdr/8Vv9APL4lpXUULdheWgGNl6DmBTJ66Albxb/vm98Uw85vaH7T/LMwIwPGBfYjbl3brVX2hPCgDPAZI+R5p3MBG6mb3VI/3SI7q2MQCo+9KQ4133OWsOXdxsMEluN25j+TFgJqcX12LpPWhA3gth/r+SFVnCysIdeiXO8eWb9d88QqWQkhc39N+yGETGWjwmsGdbbHA8ZoVtqSpuk8NyUFv5HzHH20Xq4fokXuSTvzeU6GfJzUFD7gp2wPbPcY3fy7aZ0="

services:
  - docker

cache:
  directories:
    - $HOME/.xml/


stages:
  - name: init
    if: type = cron
  - name: collect_0
    if: type = cron
  - name: collect_1
    if: type = cron
  - name: collect_2
    if: type = cron
  - name: deploy
    if: type = cron

jobs:
  include:
    - stage: init
      script: mkdir -p $HOME/.xml/ && rm -rf $HOME/.xml/*
    - stage: collect_0
      script: docker run -v $HOME/.xml/:/xml -v $PWD/WebGrab/cfgs:/data:ro --rm vk496/webgrabplus 0
    - stage: collect_1
      script: docker run -v $HOME/.xml/:/xml -v $PWD/WebGrab/cfgs:/data:ro --rm vk496/webgrabplus 1
    - stage: collect_2
      script: docker run -v $HOME/.xml/:/xml -v $PWD/WebGrab/cfgs:/data:ro --rm vk496/webgrabplus 2
    - stage: deploy
      script: bash -x .travis/deploy.sh
